public interface ScannerConstants
{

    int[] TOKEN_STATE = {-1,  0, -1, -1, 19, 20, 15, 15, 22, 18, 16, 16, 16,  7, -1, 17, -1, -1, -1, -1, -1, -1, 21, 24, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, -1, 10, 23, -1, -1, -1, -1, -1, 14, -1, -1, -1,  8, -1, -1, -1, -1, -1, -1, -1, -1, -1,  5, -1, -1, -1, -1, 11, -1, -1, -1, -1, -1, -1, -1, -1, 13, -1, -1, -1, -1, -1, -1,  4, -1,  6, -1, 12,  9,  3, -1, -1,  2 };

    String[] SCANNER_ERROR =
    {
        "Caractere não esperado",
        "",
        "Erro identificando Str",
        "Erro identificando <ignorar>",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando DEC",
        "",
        "Erro identificando FIM",
        "Erro identificando INT ou IMP ou INI",
        "Erro identificando LER",
        "Erro identificando OpBool",
        "Erro identificando REA",
        "Erro identificando SE",
        "",
        "",
        "Erro identificando NumR",
        "Erro identificando ALG",
        "Erro identificando ATR",
        "Erro identificando DEC",
        "Erro identificando ENT ou ENQ",
        "Erro identificando FIM",
        "Erro identificando IMP",
        "Erro identificando INT ou INI",
        "Erro identificando LER",
        "",
        "Erro identificando REA",
        "",
        "",
        "Erro identificando ALG",
        "Erro identificando ATR",
        "Erro identificando DEC",
        "Erro identificando ENQ",
        "Erro identificando ENT",
        "",
        "Erro identificando IMP",
        "Erro identificando INI",
        "Erro identificando INT",
        "",
        "Erro identificando REA",
        "Erro identificando ALG",
        "Erro identificando ATR",
        "Erro identificando DEC",
        "Erro identificando ENQ",
        "Erro identificando ENT",
        "Erro identificando IMP",
        "Erro identificando INI",
        "Erro identificando INT",
        "",
        "Erro identificando ALG",
        "Erro identificando ATR",
        "Erro identificando DEC",
        "Erro identificando ENQ",
        "",
        "Erro identificando IMP",
        "Erro identificando INI",
        "Erro identificando INT",
        "Erro identificando ALG",
        "Erro identificando ATR",
        "Erro identificando DEC",
        "Erro identificando ENQ",
        "Erro identificando IMP",
        "",
        "Erro identificando INT",
        "Erro identificando ALG",
        "Erro identificando ATR",
        "Erro identificando DEC",
        "Erro identificando ENQ",
        "Erro identificando IMP",
        "",
        "Erro identificando ALG",
        "",
        "Erro identificando DEC",
        "",
        "",
        "",
        "Erro identificando DEC",
        "Erro identificando DEC",
        ""
    };

}
